Add function to load YAML files
netbox-community/netbox-docker pull request #238
Opened 2020-02-05 14:36 UTC by tobiasge

This commit starts to remove some code redundancy from the startup
scripts for easier maintenance.

Related Issue:

## New Behavior
- Use shared functions in startup scripts

## Contrast to Current Behavior
- The same code is use in multible files

## Discussion: Benefits and Drawbacks
- Maintenance of script should be easier

## Changes to the Wiki
- None

## Proposed Release Note Entry
- Internal code maintenance: Started to extract redundant code into includes

## Double Check
* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

2020-02-08 09:43 UTC, cimnine requested changes
That's already a huge improvement as it is, thanks Tobias.

Some thought about how I think this could become even better:

- I don't like the module's name `includes` as it is very generic. I would suggest `startup_script_utils` or something in that direction.
- I think we should put the `def load_yaml()` into it's own file, e.g. `load.py`. Then, `__init__.py` would [import that file](https://docs.python.org/3/reference/import.html#submodules):
  ```python
  from .load import load_yaml`.
  ```
  This avoids the mistake of the past so that the `__init__.py` file does not grow into a big pile of code.
- Maybe you can add the `.editorconfig` here already, with python code indention being two spaces.

2020-02-08 09:43 UTC, cimnine commented on startup_scripts/includes/__init__.py
> +    yf = Path(yaml_file)
I believe that we should stick to one indention. You suggested to change the indention to four spaces in private. Though until we've done that everywhere we should stick to two spaces.

2020-02-08 09:43 UTC, cimnine commented on startup_scripts/includes/__init__.py
> +
Although there are other places where there are two empty lines, to me they're a waste of screen estate most of the time.

2020-02-08 09:43 UTC, cimnine commented on startup_scripts/260_ip_addresses.py
> +if ip_addresses is not None:
Maybe we can turn this `if` around:

```suggestion
if ip_addresses is None:
  sys.exit()
```

That would prevent a whole level of indention.

2020-02-10 06:54 UTC, tobiasge commented
> * I don't like the module's name `includes` as it is very generic. I would suggest `startup_script_utils` or something in that direction.
- Renamed
> * I think we should put the `def load_yaml()` into it's own file, e.g. `load.py`. Then, `__init__.py` would [import that file](https://docs.python.org/3/reference/import.html#submodules):
>   ```python
>   from .load import load_yaml`.
>   ```
>   This avoids the mistake of the past so that the `__init__.py` file does not grow into a big pile of code.
I had that thought at the beginning, but didn't implement it, because I added only one function. 
But I think you are right. We should do this correct from the beginning.

2020-02-10 13:46 UTC, cimnine approved these changes
This is such a big improvement! 😻 Thank you Tobias!

2020-02-10 18:25 UTC, merged