Add STARTTLS option.
netbox-community/netbox-docker pull request #277
Opened 2020-04-20 09:56 UTC by mbchristoff

Related Issue: none

## New Behavior

Add ability to enable STARTTLS for ldap server using the same variable as the non-docker version of NetBox.

## Contrast to Current Behavior

Add ability to enable STARTTLS using docker-compose.override.yml

## Discussion: Benefits and Drawbacks

- Easier way to enable STARTTLS instead of editing "ldap_config.py" directly.

## Changes to the Wiki

Add "AUTH_LDAP_START_TLS: "True"" or "AUTH_LDAP_START_TLS: "True"" to LDAP section of the Wiki.

## Proposed Release Note Entry

Add STARTTLS support using docker-compose.override.yml

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

2020-04-20 12:48 UTC, tobiasge requested changes
You're settings `AUTH_LDAP_START_TLS` to a string, but it should be a boolean. Have a look at how it done with `LDAP_IGNORE_CERT_ERRORS`.

2020-04-21 07:43 UTC, tobiasge commented
Ok, looks good now.
Could you squash both commits into one? Then I will merge it.

2020-04-21 08:33 UTC, mbchristoff commented
> Ok, looks good now.
> Could you squash both commits into one? Then I will merge it.
GitHub has a nice button for that, why not use that one?

2020-05-14 13:36 UTC, cimnine approved these changes

2020-05-14 14:41 UTC, merged