Fix #284 Change logic to prevent sys.exit from stopping script processing
netbox-community/netbox-docker pull request #285
Opened 2020-05-06 17:41 UTC by hpreston

Related Issue: #284

## New Behavior

Rather than running `sys.exit()` if the initializer YAML file for a startup_script is found empty, the logic is adjust to run the script if there is data found.  

## Contrast to Current Behavior

This is to prevent the stopping of following scripts should an empty data file be found. 

## Discussion: Benefits and Drawbacks

This restores the intended behavior of startup_scripts and initializers per discussions in Slack. 

## Changes to the Wiki

None Needed.

## Proposed Release Note Entry

Fixes issue where startup script processing stops when an empty data file is found.

## Double Check

* [X] I have read the comments and followed the PR template.
* [X] I have explained my PR according to the information in the comments.
* [X] My PR targets the `develop` branch.

2020-05-14 13:42 UTC, cimnine requested changes

2020-05-14 13:42 UTC, cimnine commented on startup_scripts/000_users.py
> +if not users is None:
TBH, I'm not happy with the additional nesting this is causing. But I don't know another solution out of my head either :-/

Anyways, the following notion would be preferred by me and seems to be the preferred one [by the Python community at large](https://stackoverflow.com/a/2710949/172132):

```suggestion
if users is not None:
```

2020-05-14 14:13 UTC, cimnine commented
I have implemented an alternative approach to your solution, see #294. Please see the discussion section in that PR for why I believe my approach is better then the approach suggested by you.

2020-05-15 11:58 UTC, tobiasge commented
Closed, because PR #294 was merged.

2020-05-15 11:58 UTC, closed without merging