Prefer secret to env var if both are available
netbox-community/netbox-docker pull request #291
Opened 2020-05-13 13:31 UTC by eemil

Related Issue: none

## New Behavior

If a secret and env var for the same setting are available, then prefer the secret.

## Contrast to Current Behavior

Currently, to use a secret you need to change docker-compose.yml or env/* to make sure the corresponding environment variable doesn't exist.
## Discussion: Benefits and Drawbacks

At the moment, everything I need to run netbox is defined in docker-compose.override.yml. Upgrades are easy, as I can just copy over this repo's directory with a new release. If I want to use secrets, than I need to make changes to docker-compose.yml, env/*, or use a custom compose file. With all of these methods, upgrades become more tedious.

## Changes to the Wiki

...

## Proposed Release Note Entry

Prefer secret to env var if both are available

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

2020-05-14 14:28 UTC, cimnine reviewed
Thank you for bringing this to our attention.

> than I need to make changes to docker-compose.yml

Can you explain the changes that are necessary.

TBH, I'm hesitant to switch this. Two reasons:

1. ENV vars are a good last resort. That's why I believe that they should have precedence over any other configuration methods.
2. It changes the current behavior and thous might unintentionally break current installations.

That's why I would like to learn more about the changes you have to make to the repository files. And maybe we can find another solution or maybe it convinces me that this PR is indeed necessary.

That being said, other members of our community shall feel free to pitch into the discussion. It's not just my opinion that should matter on this decision.

2020-05-14 14:28 UTC, cimnine commented on configuration/configuration.py
> +        'PASSWORD':  read_secret('redis_password', os.environ.get('REDIS_PASSWORD', '')),
```suggestion
        'PASSWORD': read_secret('redis_password', os.environ.get('REDIS_PASSWORD', '')),
```

2020-05-14 15:56 UTC, eemil commented
> >  then I need to make changes to docker-compose.yml
>
>Can you explain the changes that are necessary.

Basically, you need to make sure that the relevant env var is never set. By commenting it out from env/netbox.env, or removing the relevant env_file line from docker-compose.yml. 

If it's possible to unset env vars in docker-compose.override.yml, that would also work. But I can't come up with a way of doing this. It's not sufficient to set e.g. SUPERUSER_PASSWORD to an empty value.

> ENV vars are a good last resort. That's why I believe that they should have precedence over any other configuration methods.

Secrets are a more specific, deliberate configurable IMO. They require more configuration, and are very rarely set by default. Comparatively, env vars are often set to a default value. So if both exist, I would almost always assume that the secret is what the admin intended to be used.

> It changes the current behavior and thous might unintentionally break current installations.

For existing installations using only env vars, I don't think there should be any issues.
For installations using secrets in a broken way, there might be a problem. Take the following as an example. In this situation, the person just cloned netbox-docker and created their own docker-compose.override.yml.
```yaml
version: '3.4'
services:
  nginx:
    ports:
      - 8000:8080

  netbox:
    secrets:
      - secret_key

secrets:
  secret_key:
    file: ./secret_key
```
In this situation, netbox will silently ignore secret_key and instead use the env var from env/netbox.env. Now when the admin upgrades to a newer version of netbox-docker that gives priority to secrets, secret_key will change to value specified in ./secret_key which may cause problems (not exactly sure what the effect of this is).

So yes, some installations might break. But I think it's justified, if the installations were already in a kind-of-broken-but-still-working state. From a security standpoint, it's usually better to fail visibly than continue working in an wonky state.

2020-05-15 07:37 UTC, cimnine commented
> If it's possible to unset env vars in docker-compose.override.yml, that would also work. But I can't come up with a way of doing this. It's not sufficient to set e.g. SUPERUSER_PASSWORD to an empty value.

You should be able to just overwrite the `env_file` directive and have it point to a file of your own:

```yaml
# docker-compose.override.yml

version: '3.4'
services:
  netbox:
    env_file: env/my.netbox.env # custom env file
```

2020-05-15 08:04 UTC, eemil commented
> You should be able to just overwrite the `env_file` directive and have it point to a file of your own:

That's what I assumed at first. But what actually happens, is the env file is added in _addition_ to the existing one in docker-compose.yml. So the result is a combination of the two, with my.netbox.env having higher precedence in case of duplicate variables.

Perhaps we should wait for some more comments... maybe there's something obvious I'm missing.

2020-05-15 08:21 UTC, cimnine commented
> That's what I assumed at first. But what actually happens, is the env file is added in addition to the existing one in docker-compose.yml. So the result is a combination of the two, with my.netbox.env having higher precedence in case of duplicate variables.

Interesting.

2020-10-18 01:28 UTC, cimnine requested changes
Sorry that it took that long. At least in the meantime I've come to like your solution and your reasoning was sound anyway. Just one tiny remark, if you don't mind.

2020-10-18 01:28 UTC, cimnine commented on configuration/configuration.py
> +def read_secret(secret_name, default=''):
```suggestion
def read_secret(secret_name, default=None):
```

Is this possible? I think it's no good to have the default value of `default` be an empty string.

2020-10-18 01:28 UTC, cimnine commented on configuration/configuration.py
> +def read_secret(secret_name, default=''):
I now see that you've only copied what was there. Still, if you don't mind change it to `None`, that'd be great :)

2020-10-20 17:24 UTC, cimnine commented
Merged in 121c3f800d63f205b3ae9c1d237f030dd38c7e2b

2020-10-20 17:24 UTC, closed without merging