Rack groups have been renamed to locations
netbox-community/netbox-docker pull request #485
Opened 2021-04-07 07:18 UTC by tobiasge

## New Behavior
- Startup scripts run with Netbox 2.11

## Contrast to Current Behavior
- 

## Discussion: Benefits and Drawbacks
Updates are necessary for Netbox 2.11

## Changes to the Wiki
-

## Proposed Release Note Entry
- Compatibility with Netbox 2.11

## Double Check
* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

2021-04-07 07:26 UTC, cimnine reviewed
If I read the release notes right, then — with NB 2.11 — devices can also be assigned to a location. Maybe you could add that?

2021-04-07 07:26 UTC, cimnine commented on startup_scripts/075_locations.py
> +        print("🎨 Created rack group", location.name)
```suggestion
        print("🎨 Created location", location.name)
```

Should we change this?

2021-04-07 08:38 UTC, tobiasge commented
Changes for the change netbox-community/netbox#5284 will follow.

2021-04-07 13:43 UTC, tobiasge commented
Prerelease Checks are green now. Should be OK to review.

2021-04-13 07:41 UTC, cimnine approved these changes
Thanks for the PR. It's great to be ready when the next NetBox minor drops 🎉 I have left some remarks which you may want to consider, or maybe not.

2021-04-13 07:41 UTC, cimnine commented on initializers/vlan_groups.yml
> +#   scope_type: "dcim.region"
The quotes are not strictly necessary, are they?

2021-04-13 07:41 UTC, cimnine commented on startup_scripts/200_vlan_groups.py
> +                print("scope_type is missing from VLAN Group")
Perhaps we could add the name of the current VLAN Group to the error message to ease debugging?

2021-04-13 07:41 UTC, cimnine commented on startup_scripts/200_vlan_groups.py
> +                print(f"ContentType for app_label = '{app_label}' and model = '{model}' not found")
Here it would be good to know that this relates to a VLAN Group as well, and better if we would know which VLAN Group.

2021-04-13 13:48 UTC, cimnine requested changes
Small oversight here, no biggie :)

2021-04-13 13:48 UTC, cimnine commented on startup_scripts/200_vlan_groups.py
> +                    + "app_label = '{app_label}' and model = '{model}' not found"
```suggestion
                    + f"app_label = '{app_label}' and model = '{model}' not found"
```

2021-04-13 14:18 UTC, cimnine approved these changes

2021-04-15 05:50 UTC, tomasaberg commented
Sweet with updates, thank you for your work!
do you intend to update the groups and permissions as well, as discussed on this issue #449?

2021-04-16 17:59 UTC, tobiasge commented
[Netbox 2.11](https://github.com/netbox-community/netbox/releases/tag/v2.11.0) is released.

2021-04-16 18:00 UTC, merged