Add support for DeviceType components
netbox-community/netbox-docker pull request #742
Opened 2022-04-08 09:03 UTC by kr3ator

Related Issue: n/a

## New Behavior

This PR adds support for all of the DeviceType components like Interfaces, DeviceBays, etc. to the _190_device_type_ startup script.

## Contrast to Current Behavior

Currently there is no support for DeviceType components and there is only startup script that is available to create actual instances of these components is for interfaces.

## Discussion: Benefits and Drawbacks

This is backwards compatible. If a user wants to use this feature he only needs to extend his current _device_type.yml_ (examples therein).
Templates are supported just as when adding a component through the UI. Fields that support templating need to be suffixed with **_template**, e.g. name_template. If by mistake **name** and **name_template** keys are provided then the normal field takes precedence.

This PR assumes that #729 is merged.

## Changes to the Wiki

n/a

## Proposed Release Note Entry

Feature: Add support for device component templates to DeviceType startup script.

## Double Check

* [x] I have read the comments and followed the PR template.
* [x] I have explained my PR according to the information in the comments.
* [x] My PR targets the `develop` branch.

2022-04-08 11:17 UTC, kr3ator commented
This PR assumes that #729 is merged, until then the build pipelines will fail.

2022-04-08 12:51 UTC, cimnine requested changes
Thank you for this PR. Just one tiny remark:

Since the examples are mostly our reference documentation, I believe it would be great to have one entry where the following is true and then a comment explaining that the non-template field takes presedence.

> … if by mistake name and name_template keys are provided then the normal field takes precedence.

2022-04-08 13:13 UTC, cimnine approved these changes
Thanks

2022-04-12 08:39 UTC, kr3ator commented
@tobiasge are we good to merge this and my other 2 PRs ?

2022-04-12 11:29 UTC, merged